
#version: "3.8"

services:
  pathfinder:
      image: eqlabs/pathfinder:latest
      container_name: pathfinder_${RPC_PORT}
      restart: unless-stopped
      ports:
        - "${RPC_PORT}:9545"
      command:
        - --network=sepolia
        - --http-rpc=0.0.0.0:9545
      volumes:
        - pathfinder_data:/data
      environment:
        - TZ=Etc/UTC
volumes:
  pathfinder_data: